CREATE TABLE CLIENTES
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR NOT NULL,
CPF CHAR(11) NOT NULL,
RG CHAR(7) NOT NULL,
TELEFONE CHAR(11) NOT NULL,
ENDEREÇO VARCHAR NOT NULL,
EMAIL VARCHAR NOT NULL,
ESPECIAL BIT NOT NULL,
CONSTRAINT UQ_CLIENTES UNIQUE (CPF)
)
CREATE TABLE FUNCIONARIOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR NOT NULL,
CPF CHAR(11) NOT NULL,
RG CHAR(7) NOT NULL,
TELEFONE CHAR(11) NOT NULL,
ENDEREÇO VARCHAR NOT NULL,
EMAIL VARCHAR NOT NULL,
SENHASISTEMA VARCHAR NOT NULL,
CONSTRAINT UQ_FUNCIONARIOSCPF UNIQUE (CPF),
CONSTRAINT UQ_FUNCIONARIOSEMAIL UNIQUE (EMAIL)
)
CREATE TABLE FORNECEDORES
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR NOT NULL,
CNPJ CHAR(11) NOT NULL,
TELEFONE CHAR(11) NOT NULL,
EMAIL VARCHAR NOT NULL,
TIPOFUNCIONARIO VARCHAR NOT NULL,
CONSTRAINT UQ_FORNECEDORES UNIQUE (CNPJ)
)
CREATE TABLE PRODUTOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR NOT NULL,
PRECO FLOAT NOT NULL,
ESTOQUE CHAR NOT NULL,
DATAVALIDADE DATETIME NOT NULL,
FORNECEDORID INT NOT NULL,
CONSTRAINT FK_FORNECEDOR_PRODUTO FOREIGN KEY (FORNECEDORID)
REFERENCES FORNECEDORES,
)
CREATE TABLE TIPOQUARTOS
(
ID INT PRIMARY KEY IDENTITY,
ARCONDICIONADO BIT NOT NULL,
SUITEEXTRA BIT NOT NULL,
TELEVISAO BIT NOT NULL,
ESPECIAL BIT NOT NULL,
)
CREATE TABLE QUARTOS
(
ID INT PRIMARY KEY IDENTITY,
VALORBASE FLOAT NOT NULL,
RESERVA BIT NOT NULL,
NUMQUARTO VARCHAR NOT NULL,
CATEGOTIAS INT NOT NULL,
TIPOQUARTOID INT NOT NULL,
ESTAOCUPADO BIT NOT NULL,
CONSTRAINT FK_TIPOQUARTOS_QUARTO FOREIGN KEY (TIPOQUARTOID)
REFERENCES TIPOQUARTOS
)
CREATE TABLE ENTRADA_PRODUTOS
(
ID INT PRIMARY KEY IDENTITY,
DATAENTRADA DATETIME NOT NULL,
FUNCIONARIOID INT NOT NULL,
TOTAL FLOAT NOT NULL,
FORNECEDORID INT NOT NULL,
CONSTRAINT FK_ENTRADA_PRODUTOS_FUNCIONARIOS FOREIGN KEY (FUNCIONARIOID)
REFERENCES FUNCIONARIOS,
CONSTRAINT FK_ENTRADA_PRODUTOS_FORNECEDOR FOREIGN KEY (FORNECEDORID)
REFERENCES FORNECEDORES,
)
CREATE TABLE ITENS_ENTRADA
(
PRODUTOID INT NOT NULL,
ENTRADAID INT NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO FLOAT NOT NULL,
CONSTRAINT FK_ITENS_ENTRADA_ENTRADA_PRODUTOS FOREIGN KEY (ENTRADAID)
REFERENCES ENTRADA_PRODUTOS,
CONSTRAINT FK_ITENS_ENTRADA_PRODUTOS FOREIGN KEY (PRODUTOID)
REFERENCES PRODUTOS,
)
CREATE TABLE SAIDA_PRODUTOS
(
ID INT PRIMARY KEY IDENTITY,
DATASAIDA DATETIME NOT NULL,
FUNCIONARIOID INT NOT NULL,
TOTAL FLOAT NOT NULL,
CLIENTEID INT NOT NULL,
CONSTRAINT FK_SAIDA_PRODUTOS_FUNCIONARIOS FOREIGN KEY (FUNCIONARIOID)
REFERENCES FUNCIONARIOS,
CONSTRAINT FK_SAIDA_PRODUTOS_CLIENTE FOREIGN KEY (CLIENTEID)
REFERENCES CLIENTES,
)
CREATE TABLE ITENS_SAIDA
(
PRODUTOID INT NOT NULL,
SAIDAID INT NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO FLOAT NOT NULL,
CONSTRAINT FK_ITENS_SAIDA_SAIDA_PRODUTO FOREIGN KEY (SAIDAID)
REFERENCES SAIDA_PRODUTOS,
CONSTRAINT FK_ITENS_SAIDA_PRODUTO FOREIGN KEY (PRODUTOID)
REFERENCES PRODUTOS,
)
